import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { useForm } from '@inertiajs/react';

export interface CompanyInfo {
    company_name: string;
    company_gst: string;
    company_address: string;
    company_phone: string;
}

interface Props {
    companyInfo: CompanyInfo;
}

export default function CompanyInfoTab({ companyInfo }: Props) {
    const form = useForm<CompanyInfo>({
        company_name: companyInfo.company_name,
        company_gst: companyInfo.company_gst,
        company_address: companyInfo.company_address,
        company_phone: companyInfo.company_phone,
    });

    function handleSubmit(e: React.FormEvent) {
        e.preventDefault();
        form.patch(route('system-settings.company'));
    }

    return (
        <Card>
            <CardHeader>
                <CardTitle className="text-base font-semibold">Company Information</CardTitle>
                <CardDescription>
                    These details appear on invoices, salary slips, and other documents generated by the system.
                </CardDescription>
            </CardHeader>
            <CardContent>
                <form onSubmit={handleSubmit} className="space-y-4">
                    <div className="space-y-1.5">
                        <Label htmlFor="company_name">Company Name</Label>
                        <Input
                            id="company_name"
                            value={form.data.company_name}
                            onChange={(e) => form.setData('company_name', e.target.value)}
                            placeholder="Acme Pvt. Ltd."
                        />
                        {form.errors.company_name && (
                            <p className="text-destructive text-xs">{form.errors.company_name}</p>
                        )}
                    </div>

                    <div className="space-y-1.5">
                        <Label htmlFor="company_gst">GST Number</Label>
                        <Input
                            id="company_gst"
                            value={form.data.company_gst}
                            onChange={(e) => form.setData('company_gst', e.target.value)}
                            placeholder="22AAAAA0000A1Z5"
                        />
                        {form.errors.company_gst && (
                            <p className="text-destructive text-xs">{form.errors.company_gst}</p>
                        )}
                    </div>

                    <div className="space-y-1.5">
                        <Label htmlFor="company_address">Address</Label>
                        <Textarea
                            id="company_address"
                            value={form.data.company_address}
                            onChange={(e) => form.setData('company_address', e.target.value)}
                            placeholder="123 Main Street, City, State – 400001"
                            rows={3}
                        />
                        {form.errors.company_address && (
                            <p className="text-destructive text-xs">{form.errors.company_address}</p>
                        )}
                    </div>

                    <div className="space-y-1.5">
                        <Label htmlFor="company_phone">Office Phone</Label>
                        <Input
                            id="company_phone"
                            value={form.data.company_phone}
                            onChange={(e) => form.setData('company_phone', e.target.value)}
                            placeholder="+91 98765 43210"
                        />
                        {form.errors.company_phone && (
                            <p className="text-destructive text-xs">{form.errors.company_phone}</p>
                        )}
                    </div>

                    <Button type="submit" size="sm" disabled={form.processing}>
                        {form.processing ? 'Saving…' : 'Save Company Info'}
                    </Button>
                </form>
            </CardContent>
        </Card>
    );
}
